### ISSUE TITLE
There is an error when testing the CNN model

### ISSUE THREAD

**Issue by sunwei925** [VCLLab/IFQA#10]
python test.py --f_path=docs/00021_Blurred.png --model CNN
Namespace(f_path='docs/00021_Blurred.png', model='CNN')
Traceback (most recent call last):
  File "test.py", line 93, in <module>
    main(config)
  File "test.py", line 75, in main
    discriminator = get_model(model_name)
  File "test.py", line 70, in get_model
    discriminator.load_state_dict(torch.load(model_file_path)['D'])
  File "/home/sunwei/miniconda3/envs/pytorch12/lib/python3.8/site-packages/torch/serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/sunwei/miniconda3/envs/pytorch12/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by SongDoHou** [comment]
Sorry for late reply. 
i think the model file you downloaded is corrupted .. Can you download again and retry?
