### ISSUE TITLE
There is an error when testing the ViT model

### ISSUE THREAD

**Issue by sunwei925** [VCLLab/IFQA#9]
python test.py --f_path=docs/00021_Blurred.png
Namespace(f_path='docs/00021_Blurred.png', model='VIT')
Traceback (most recent call last):
  File "test.py", line 93, in <module>
    main(config)
  File "test.py", line 75, in main
    discriminator = get_model(model_name)
  File "test.py", line 62, in get_model
    model = MaskedAutoencoderViT()
  File "/home/sunwei/code/IQA/IFQA/model_huge.py", line 26, in __init__
    self.blocks = nn.ModuleList([
  File "/home/sunwei/code/IQA/IFQA/model_huge.py", line 27, in <listcomp>
    Block(embed_dim, num_heads, mlp_ratio, qkv_bias=True, qk_scale=None, norm_layer=norm_layer)
TypeError: __init__() got an unexpected keyword argument 'qk_scale'

**Comment by SongDoHou** [comment]
So sorry for late reply. I think it is related to timm version. What version are you using now?
Can you try timm with 0.3.2?
